services:
  - type: web
    name: timesheet-middleware
    runtime: python
    pythonVersion: 3.10
    buildCommand: |
      pip install --upgrade pip
      pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    healthCheckPath: /
    region: singapore
    plan: free