services:
  - type: web
    name: timesheet-middleware
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env: python
    pythonVersion: 3.11.7
    plan: free
    region: oregon
    branch: main
    autoDeploy: true