services:
  - type: web
    name: timesheet-middleware
    env: python
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    region: singapore
    plan: free